# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InsertWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from mysql.connector import MySQLConnection, Error
from python_mysql_dbconfig import read_db_config

class Ui_InsertWindow(object):
    def setupUi(self, InsertWindow):

        InsertWindow.setObjectName("InsertWindow")
        InsertWindow.resize(375, 340)

        self.textEditInsertId = QtWidgets.QTextEdit(InsertWindow)
        self.textEditInsertId.setGeometry(QtCore.QRect(190, 20, 151, 31))
        self.textEditInsertId.setObjectName("textEditInsertId")

        self.label = QtWidgets.QLabel(InsertWindow)
        self.label.setGeometry(QtCore.QRect(20, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")

        self.textEditInsertNombre = QtWidgets.QTextEdit(InsertWindow)
        self.textEditInsertNombre.setGeometry(QtCore.QRect(190, 70, 151, 31))
        self.textEditInsertNombre.setObjectName("textEditInsertNombre")

        self.label_2 = QtWidgets.QLabel(InsertWindow)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")

        self.textEditInsertPrecio = QtWidgets.QTextEdit(InsertWindow)
        self.textEditInsertPrecio.setGeometry(QtCore.QRect(190, 120, 151, 31))
        self.textEditInsertPrecio.setObjectName("textEditInsertPrecio")

        self.label_3 = QtWidgets.QLabel(InsertWindow)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")

        self.textEditInsertPaginas = QtWidgets.QTextEdit(InsertWindow)
        self.textEditInsertPaginas.setGeometry(QtCore.QRect(190, 170, 151, 31))
        self.textEditInsertPaginas.setObjectName("textEditInsertPaginas")

        self.label_4 = QtWidgets.QLabel(InsertWindow)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")

        self.textoActualizacionInsert = QtWidgets.QLabel(InsertWindow)
        self.textoActualizacionInsert.setGeometry(QtCore.QRect(30, 290, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textoActualizacionInsert.setFont(font)
        self.textoActualizacionInsert.setText("")
        self.textoActualizacionInsert.setAlignment(QtCore.Qt.AlignCenter)
        self.textoActualizacionInsert.setObjectName("textoActualizacionInsert")

        self.botonInsertLibro = QtWidgets.QPushButton(InsertWindow)
        self.botonInsertLibro.setGeometry(QtCore.QRect(10, 240, 341, 28))
        self.botonInsertLibro.setObjectName("botonInsertLibro")
        self.botonInsertLibro.clicked.connect(self.clickInsertar)

        self.retranslateUi(InsertWindow)
        QtCore.QMetaObject.connectSlotsByName(InsertWindow)

    def retranslateUi(self, InsertWindow):
        _translate = QtCore.QCoreApplication.translate
        InsertWindow.setWindowTitle(_translate("InsertWindow", "Insert"))
        self.botonInsertLibro.setText(_translate("InsertWindow", "Insert"))
        self.label.setText(_translate("InsertWindow", "Id :"))
        self.label_2.setText(_translate("InsertWindow", "Nombre :"))
        self.label_3.setText(_translate("InsertWindow", "Precio :"))
        self.label_4.setText(_translate("InsertWindow", "Paginas :"))

    def clickInsertar(self):
        id = int(self.textEditInsertId.toPlainText())
        nombre = str(self.textEditInsertNombre.toPlainText())
        precio = int(self.textEditInsertPrecio.toPlainText())
        paginas = int(self.textEditInsertPaginas.toPlainText())
        
        query = "INSERT INTO libros(idLibros, nombre, precio, paginas) " \
            "VALUES(%s,%s,%s,%s)"
        args = (id, nombre, precio,paginas)

        try:
            db_config = read_db_config()
            conn = MySQLConnection(**db_config)

            cursor = conn.cursor()
            cursor.execute(query, args)
            #cursor.executemany(arreglo) #Para insertar varias cosas al mismo tiempo

            self.textoActualizacionInsert.setText("Se inserto el libro")

            if cursor.lastrowid:
                print('last insert id', cursor.lastrowid)
            else:
                print('last insert id not found')

            conn.commit()
        except Error as error:
            print(error)

        finally:
            cursor.close()
            conn.close()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InsertWindow = QtWidgets.QWidget()
    ui = Ui_InsertWindow()
    ui.setupUi(InsertWindow)
    InsertWindow.show()
    sys.exit(app.exec_())
