# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from mysql.connector import MySQLConnection, Error
from python_mysql_dbconfig import read_db_config
from SelectWindow import Ui_SelectWindow
from InsertWindow import Ui_InsertWindow
from UpdateWindow import Ui_UpdateWindow
from DeleteWindow import Ui_DeleteWindow


class Ui_MainWindow(object):
    def connect():
        """ Connect to MySQL database """

        db_config = read_db_config()
        conn = None
        try:
            print('Connecting to MySQL database...')
            conn = MySQLConnection(**db_config)

            if conn.is_connected():
                print('Connection established.')
            else:
                print('Connection failed.')

        except Error as error:
            print(error)

        finally:
            if conn is not None and conn.is_connected():
                conn.close()
                print('Connection closed.')

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(493, 194)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.texto1 = QtWidgets.QLabel(self.centralwidget)
        self.texto1.setGeometry(QtCore.QRect(0, 10, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.texto1.setFont(font)
        self.texto1.setScaledContents(False)
        self.texto1.setAlignment(QtCore.Qt.AlignCenter)
        self.texto1.setWordWrap(True)
        self.texto1.setObjectName("texto1")

        self.botonInsert = QtWidgets.QPushButton(self.centralwidget)
        self.botonInsert.setGeometry(QtCore.QRect(130, 80, 111, 61))
        self.botonInsert.setObjectName("botonInsert")
        self.botonInsert.clicked.connect(self.AbrirInsertWindow)

        self.botonUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.botonUpdate.setGeometry(QtCore.QRect(250, 80, 111, 61))
        self.botonUpdate.setObjectName("botonUpdate")
        self.botonUpdate.clicked.connect(self.AbrirUpdateWindow)

        self.botonSelect = QtWidgets.QPushButton(self.centralwidget)
        self.botonSelect.setGeometry(QtCore.QRect(10, 80, 111, 61))
        self.botonSelect.setObjectName("botonSelect")
        self.botonSelect.clicked.connect(self.AbrirSelectWindow)

        self.botonDelete = QtWidgets.QPushButton(self.centralwidget)
        self.botonDelete.setGeometry(QtCore.QRect(370, 80, 111, 61))
        self.botonDelete.setObjectName("botonDelete")
        self.botonDelete.clicked.connect(self.AbrirDeleteWindow)

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 493, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EI6"))
        self.botonInsert.setText(_translate("MainWindow", "Insert Libro"))
        self.texto1.setText(_translate("MainWindow", "Libros y Autores"))
        self.botonUpdate.setText(_translate("MainWindow", "Update Libro"))
        self.botonSelect.setText(_translate("MainWindow", "Select"))
        self.botonDelete.setText(_translate("MainWindow", "Delete Libro"))

    def AbrirSelectWindow(self):
        self.win  = QtWidgets.QMainWindow()
        self.ui = Ui_SelectWindow()
        self.ui.setupUi(self.win)
        self.win.show()
    
    def AbrirInsertWindow(self):
        self.win  = QtWidgets.QMainWindow()
        self.ui = Ui_InsertWindow()
        self.ui.setupUi(self.win)
        self.win.show()
    
    def AbrirUpdateWindow(self):
        self.win  = QtWidgets.QMainWindow()
        self.ui = Ui_UpdateWindow()
        self.ui.setupUi(self.win)
        self.win.show()

    def AbrirDeleteWindow(self):
        self.win  = QtWidgets.QMainWindow()
        self.ui = Ui_DeleteWindow()
        self.ui.setupUi(self.win)
        self.win.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    Ui_MainWindow.connect()
    sys.exit(app.exec_())
    
