# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mysql.connector import MySQLConnection, Error
from python_mysql_dbconfig import read_db_config


class Ui_SelectWindow(object):

    def setupUi(self, SelectWindow):
        SelectWindow.setObjectName("SelectWindow")
        SelectWindow.resize(484, 481)

        self.label = QtWidgets.QLabel(SelectWindow)
        self.label.setGeometry(QtCore.QRect(0, 10, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(SelectWindow)
        self.label_2.setGeometry(QtCore.QRect(0, 80, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.textEdit = QtWidgets.QTextEdit(SelectWindow)
        self.textEdit.setGeometry(QtCore.QRect(130, 20, 251, 31))
        self.textEdit.setObjectName("textEdit")

        self.checkBoxAutores = QtWidgets.QCheckBox(SelectWindow)
        self.checkBoxAutores.setGeometry(QtCore.QRect(240, 100, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxAutores.setFont(font)
        self.checkBoxAutores.setObjectName("checkBoxAutores")
        self.checkBoxAutores.stateChanged.connect(self.cambioCheck)

        self.checkBoxLibros = QtWidgets.QCheckBox(SelectWindow)
        self.checkBoxLibros.setGeometry(QtCore.QRect(130, 100, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxLibros.setFont(font)
        self.checkBoxLibros.setObjectName("checkBoxLibros")
        self.checkBoxLibros.stateChanged.connect(self.cambioCheck)

        self.checkBoxTelefonos = QtWidgets.QCheckBox(SelectWindow)
        self.checkBoxTelefonos.setGeometry(QtCore.QRect(360, 100, 101, 20))
        self.checkBoxTelefonos.stateChanged.connect(self.cambioCheck)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxTelefonos.setFont(font)
        self.checkBoxTelefonos.setObjectName("checkBoxTelefonos")

        self.botonConsultarSelect = QtWidgets.QPushButton(SelectWindow)
        self.botonConsultarSelect.setGeometry(QtCore.QRect(20, 150, 451, 28))
        self.botonConsultarSelect.setObjectName("botonConsultarSelect")
        self.botonConsultarSelect.clicked.connect(self.ClickConsultar)

        self.scrollArea = QtWidgets.QScrollArea(SelectWindow)
        self.scrollArea.setGeometry(QtCore.QRect(20, 200, 451, 261))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 449, 259))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.listaSelect = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.listaSelect.setGeometry(QtCore.QRect(0, 0, 451, 261))
        self.listaSelect.setObjectName("listaSelect")

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(SelectWindow)
        QtCore.QMetaObject.connectSlotsByName(SelectWindow)

    def retranslateUi(self, SelectWindow):
        _translate = QtCore.QCoreApplication.translate
        SelectWindow.setWindowTitle(_translate("SelectWindow", "Select"))
        self.label.setText(_translate("SelectWindow", "Select"))
        self.label_2.setText(_translate("SelectWindow", "From"))
        self.checkBoxAutores.setText(_translate("SelectWindow", "Autores"))
        self.checkBoxLibros.setText(_translate("SelectWindow", "Libros"))
        self.checkBoxTelefonos.setText(_translate("SelectWindow", "Telefonos"))
        self.botonConsultarSelect.setText(_translate("SelectWindow", "Consultar"))

    def cambioCheck(self):
        tabla = ""
        if self.checkBoxAutores.isChecked()==True:
            tabla = "autor"
        if self.checkBoxLibros.isChecked()==True:
            tabla = "libros"
        if self.checkBoxTelefonos.isChecked()==True:
            tabla = "telefono"
        return tabla

    def ClickConsultar(self):
        columna = str(self.textEdit.toPlainText())
        tabla = self.cambioCheck()
        
        try:
            dbconfig = read_db_config()
            conn = MySQLConnection(**dbconfig)
            cursor = conn.cursor()
            cursor.execute("SELECT " + columna + " FROM " + tabla)
            rows = cursor.fetchall() #guarda todas las filas  como un arreglo

            print('Total Row(s):', cursor.rowcount)
            for row in rows:
                self.listaSelect.setText('\n'.join(map(str, rows)))

        except Error as e:
            print(e)

        finally:
            cursor.close()
            conn.close()
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SelectWindow = QtWidgets.QWidget()
    ui = Ui_SelectWindow()
    ui.setupUi(SelectWindow)
    SelectWindow.show()
    sys.exit(app.exec_())
